name: judahshop
favicon: null
layout_spectrum: 0.7571851008106023
typography_spectrum: 0.8199066645465791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.014544762903824449
  lightness: 0.4110927735455334
  saturation: 0.9032702897675335
  rhythmicContrast: 0.8778551737777889
purpose: []
